ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER MARKETER IDENTIFIED BY marketing123;

GRANT CONNECT TO MARKETER;
GRANT CREATE SESSION TO MARKETER;

-- 1단계: PDB로 세션 변경
ALTER SESSION SET CONTAINER = XEPDB1;

-- 2단계: 현재 컨테이너 확인
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') FROM DUAL;

-- 3단계: 사용자 생성
CREATE USER HAHA2 IDENTIFIED BY 1234;

-- 4단계: 권한 부여
GRANT CREATE SESSION TO HAHA2;
GRANT CONNECT TO HAHA2;  -- 추가 권한


CONN HAHA2/1234@localhost:1521/XEPDB1;